name: 'clean-workspace-github-action'
description: 'This action cleans the workspace.'

runs:
  using: "composite"
  steps:
    - name: Clean up workspace
      if: always()
      shell: bash
      post: git reset --hard HEAD && git clean -fdx

branding:
  icon: "box"
  color: "orange"
